services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: nginx:stable-alpine
    ports:
      - "9000:80"
    volumes:
      - ./catalogo_de_filmes:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app